"""Stable physical constants for Digital Forge Futurewear."""

MODULAR_STANDARD_VERSION = "DF-MOD-1.0"

MIN_FDM_FEATURE_MM = 0.8
MIN_FDM_CHAMFER_MM = 0.45
MIN_DOCK_KEY_OFFSET_MM = 0.8
MAX_COMPATIBLE_PRINTER_COMPENSATION_MM = 0.35

MIN_CONNECTOR_CLEARANCE_MM = 0.15
MAX_CONNECTOR_CLEARANCE_MM = 0.75
DEFAULT_CLEARANCE_STEP_MM = 0.10

DEFAULT_COUPON_TAB_LENGTH_MM = 18.0
DEFAULT_COUPON_TAB_WIDTH_EXTRA_MM = 10.0
DEFAULT_COUPON_BASE_THICKNESS_MM = 4.0
