"""Streamlit gallery of ready-to-download sword configurations."""

import streamlit as st

from showcase_presets import SHOWCASE_PRESETS, generate_showcase_scad, preset_metrics


st.set_page_config(page_title="Preset Gallery | Digital Forge", page_icon="DF", layout="wide")
st.title("Preset Gallery")
st.caption("Named configurations generated by the same OpenSCAD generator as the designer.")

columns = st.columns(2)
for index, preset in enumerate(SHOWCASE_PRESETS):
    scad = generate_showcase_scad(preset)
    metrics = preset_metrics(preset)
    with columns[index % 2]:
        with st.container(border=True):
            st.subheader(preset.name)
            st.write(preset.description)
            st.caption(
                f"{preset.sword_type.replace('_', ' ').title()} · "
                f"{preset.blade_style.title()} blade · {preset.guard_style.title()} guard · "
                f"{preset.pommel_style.title()} pommel"
            )
            st.write(
                f"Blade {metrics['blade_length_mm']:g} × {metrics['blade_base_width_mm']:g} mm · "
                f"Grip {metrics['grip_length_mm']:g} mm"
            )
            with st.expander("View generated OpenSCAD"):
                st.code(scad, language="openscad")
            st.download_button(
                "Download .scad",
                data=scad,
                file_name=f"{preset.slug}.scad",
                mime="text/plain",
                key=f"download_{preset.slug}",
            )

st.info("Open **Digital Forge Version 4** in the page navigation to create a custom design.")
